[package]
name = "dmcfe"
version = "0.1.0"
edition = "2018"

[dependencies]
cosmian_bls12_381 = {git = "https://github.com/Cosmian/bls12_381.git", branch = "add_gt_hash"}
cosmian_mcfe = { path = "crates/mcfe" }
rand = "0.8"
sha2 = "0.9"
eyre = "0.6"
subtle = "2.4"
