[package]
name = "dmcfe"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = {git = "https://github.com/Cosmian/bls12_381.git", branch = "tbrezot/add_g1_tools"}
rand = "*"
